import math
from typing import Any, Dict, List

from app.agents.base import BaseAgent
from app.services import embeddings, ingestion, groq_client
from app.services.chroma_client import get_documents_collection

SYSTEM_PROMPT = (
    "You are the Knowledge Agent for AtlasAI, an industrial knowledge "
    "assistant. Answer the technician's question using ONLY the provided "
    "context chunks. Cite sources inline using [1], [2] etc matching the "
    "chunk numbers given. If the context doesn't contain the answer, say "
    "so plainly instead of guessing. Reply in the same language/style as "
    "the question (English, Hindi, or Hinglish). Keep it concise and "
    "field-usable — a technician may be reading this on a phone mid-shift."
)


def _distance_to_confidence(distance: float) -> float:
    cos_sim = 1 - distance / 2
    return max(0.0, min(1.0, cos_sim))


class KnowledgeAgent(BaseAgent):
    """Answers operational/procedural questions using RAG over documents,
    lightly boosted by equipment-tag matching (a stand-in for full
    Knowledge Graph traversal until the backend has Firestore Admin
    access)."""

    name = "knowledge_agent"

    async def handle(self, request: Dict[str, Any]) -> Dict[str, Any]:
        query = request.get("query", "")
        context = request.get("context", {})
        equipment_id = context.get("equipment_id")

        collection = get_documents_collection()
        if collection.count() == 0:
            return {
                "agent": self.name,
                "answer": "No documents have been ingested yet, so I have nothing to ground an answer in.",
                "confidence": 0.0,
                "sources": [],
                "reasoning": "Chroma `documents` collection is empty.",
            }

        query_vec = await embeddings.embed(query)
        n_results = min(8, collection.count())
        results = collection.query(
            query_embeddings=[query_vec],
            n_results=n_results,
            include=["documents", "metadatas", "distances"],
        )

        docs = results["documents"][0]
        metas = results["metadatas"][0]
        dists = results["distances"][0]

        query_tags = set(ingestion.extract_equipment_tags(query))
        if equipment_id:
            query_tags.add(equipment_id.upper())

        ranked = list(zip(docs, metas, dists))
        if query_tags:
            ranked.sort(key=lambda item: 0 if item[1].get("equipment_id", "") in query_tags else 1)

        top = ranked[:5]

        context_lines = []
        sources = []
        for i, (doc_text, meta, _dist) in enumerate(top, start=1):
            context_lines.append(f"[{i}] {doc_text}")
            page = meta.get("page", "?")
            fname = meta.get("file_name", "unknown")
            sources.append(f"{fname} (page {page})")

        context_block = "\n\n".join(context_lines)
        user_prompt = f"Context:\n{context_block}\n\nQuestion: {query}"

        avg_confidence = sum(_distance_to_confidence(d) for _, _, d in top) / len(top)

        try:
            answer = await groq_client.chat_completion(SYSTEM_PROMPT, user_prompt)
            reasoning = (
                f"Retrieved {len(top)} chunks via semantic search"
                + (f", boosted by equipment tag(s) {sorted(query_tags)}" if query_tags else "")
                + ". Answer generated by Llama 3.3 70B (Groq), grounded strictly in retrieved context."
            )
        except Exception as e:
            answer = "Groq generation unavailable (" + str(e) + "). Top matching passage: " + top[0][0][:400]
            reasoning = f"Retrieved {len(top)} chunks via semantic search; LLM generation step failed, showing extractive fallback."

        return {
            "agent": self.name,
            "answer": answer,
            "confidence": round(avg_confidence, 2),
            "sources": sources,
            "reasoning": reasoning,
        }
