from typing import Any, Dict

from app.agents.base import BaseAgent
from app.services import groq_client, retrieval

SYSTEM_PROMPT = (
    "You are the Knowledge Agent for AtlasAI, an industrial knowledge "
    "assistant. Answer the technician's question using ONLY the provided "
    "context chunks. Cite sources inline using [1], [2] etc matching the "
    "chunk numbers given. If the context doesn't contain the answer, say "
    "so plainly instead of guessing. Reply in the same language/style as "
    "the question (English, Hindi, or Hinglish). Keep it concise and "
    "field-usable — a technician may be reading this on a phone mid-shift."
)


class KnowledgeAgent(BaseAgent):
    name = "knowledge_agent"

    async def handle(self, request: Dict[str, Any]) -> Dict[str, Any]:
        query = request.get("query", "")
        context = request.get("context", {})
        equipment_id = context.get("equipment_id")

        r = await retrieval.retrieve(query, equipment_id=equipment_id, n_results=8, top_k=5)

        if not r["top"]:
            return {
                "agent": self.name,
                "answer": "No documents have been ingested yet, so I have nothing to ground an answer in.",
                "confidence": 0.0,
                "sources": [],
                "reasoning": "Chroma `documents` collection is empty.",
            }

        user_prompt = f"Context:\n{r['context_block']}\n\nQuestion: {query}"

        try:
            answer = await groq_client.chat_completion(SYSTEM_PROMPT, user_prompt)
            reasoning = (
                f"Retrieved {len(r['top'])} chunks via semantic search"
                + (f", boosted by equipment tag(s) {sorted(r['tags'])}" if r["tags"] else "")
                + ". Answer generated by Llama 3.3 70B (Groq), grounded strictly in retrieved context."
            )
        except Exception as e:
            answer = "Groq generation unavailable (" + str(e) + "). Top matching passage: " + r["top"][0][0][:400]
            reasoning = f"Retrieved {len(r['top'])} chunks via semantic search; LLM generation step failed, showing extractive fallback."

        return {
            "agent": self.name,
            "answer": answer,
            "confidence": r["confidence"],
            "sources": r["sources"],
            "reasoning": reasoning,
        }
