from typing import Any, Dict

from app.agents.base import BaseAgent
from app.services import groq_client, retrieval

SYSTEM_PROMPT = """
You are AtlasAI's Industrial Maintenance Knowledge Agent.

You are helping maintenance engineers troubleshoot industrial equipment.

Use ONLY the retrieved context below.
Never invent facts that are not supported by the retrieved documents.

When answering, ALWAYS follow this format whenever the information exists:

Problem Summary:
- Briefly describe the issue.

Root Cause:
- Explain the likely cause.

Corrective Actions:
- List the immediate maintenance actions required.

Preventive Maintenance:
- List the preventive steps to avoid recurrence.

Safety Precautions:
- Mention any safety precautions from the documents.

References:
- Cite sources like [1], [2].

If the document does not explicitly mention corrective or preventive actions,
say:
"Corrective actions are not explicitly mentioned in the retrieved documents."

Reply in the same language as the user's question.
Keep the answer concise and technician-friendly.
"""

class KnowledgeAgent(BaseAgent):
    name = "knowledge_agent"

    async def handle(self, request: Dict[str, Any]) -> Dict[str, Any]:
        query = request.get("query", "")
        context = request.get("context", {})
        equipment_id = context.get("equipment_id")

        r = await retrieval.retrieve(query, equipment_id=equipment_id, n_results=15, top_k=10)

        if not r["top"]:
            return {
                "agent": self.name,
                "answer": "No documents have been ingested yet, so I have nothing to ground an answer in.",
                "confidence": 0.0,
                "sources": [],
                "reasoning": "Chroma `documents` collection is empty.",
            }

        user_prompt = f"""
        Retrieved Documents:

        {r['context_block']}

        Technician Question:

        {query}

        Provide:

        1. Problem Summary
        2. Root Cause
        3. Corrective Actions
        4. Preventive Maintenance
        5. Safety Precautions
        6. References
        """

        try:
            answer = await groq_client.chat_completion(SYSTEM_PROMPT, user_prompt)
            reasoning = (
                f"Retrieved {len(r['top'])} chunks via semantic search"
                + (f", boosted by equipment tag(s) {sorted(r['tags'])}" if r["tags"] else "")
                + ". Answer generated by Llama 3.3 70B (Groq), grounded strictly in retrieved context."
            )
        except Exception as e:
            answer = "Groq generation unavailable (" + str(e) + "). Top matching passage: " + r["top"][0][0][:400]
            reasoning = f"Retrieved {len(r['top'])} chunks via semantic search; LLM generation step failed, showing extractive fallback."

        return {
            "agent": self.name,
            "answer": answer,
            "confidence": r["confidence"],
            "sources": r["sources"],
            "reasoning": reasoning,
        }
