from typing import Any, Dict

from app.agents.base import BaseAgent
from app.services import groq_client, retrieval

SYSTEM_PROMPT = (
    "You are the Maintenance Agent for AtlasAI. You reason over equipment "
    "history and inspection records to support root-cause analysis and "
    "predictive maintenance. Using ONLY the provided context entries, "
    "identify failure patterns, likely root causes, and recommended "
    "maintenance actions for the equipment in question. Cite entries "
    "inline as [1], [2] etc. If the history doesn't support a clear "
    "conclusion, say so rather than speculating. Be concise and "
    "field-usable."
)


class MaintenanceAgent(BaseAgent):
    name = "maintenance_agent"

    async def handle(self, request: Dict[str, Any]) -> Dict[str, Any]:
        query = request.get("query", "")
        context = request.get("context", {})
        equipment_id = context.get("equipment_id")

        r = await retrieval.retrieve(
            query, equipment_id=equipment_id, n_results=8, top_k=5,
            require_equipment_match=True,
        )

        if not r["top"]:
            return {
                "agent": self.name,
                "answer": "No equipment history/documents ingested yet — nothing to reason over.",
                "confidence": 0.0,
                "sources": [],
                "reasoning": "Chroma `documents` collection is empty.",
            }

        note = (
            "" if r["tags"] else
            " (no specific equipment identified in the query — showing closest general matches)"
        )
        user_prompt = f"Context (equipment history / inspection entries):\n{r['context_block']}\n\nQuestion: {query}{note}"

        try:
            answer = await groq_client.chat_completion(SYSTEM_PROMPT, user_prompt)
            reasoning = (
                f"Retrieved {len(r['top'])} history entries"
                + (f" for equipment {sorted(r['tags'])}" if r["tags"] else " via open semantic search (no equipment tag detected)")
                + ". Root-cause reasoning generated by Llama 3.3 70B (Groq), grounded in retrieved entries."
            )
        except Exception as e:
            answer = "Groq generation unavailable (" + str(e) + "). Closest matching entry: " + r["top"][0][0][:400]
            reasoning = f"Retrieved {len(r['top'])} entries; LLM generation failed, showing extractive fallback."

        return {
            "agent": self.name,
            "answer": answer,
            "confidence": r["confidence"],
            "sources": r["sources"],
            "reasoning": reasoning,
        }
